"""
Monotonically-constrained gradient-boosted tree ensemble.  Blueprint 9.4.

"Monotonic constraints mean 'HIGHER RESPIRATORY RATE NEVER LOWERS RISK' is a
PROPERTY OF THE MODEL, not a hope."

Blueprint 6.2: "Model is a small gradient-boosted ensemble with monotonic
constraints on every physiological feature, so DIRECTION OF EFFECT IS GUARANTEED
RATHER THAN ESTIMATED."

Written in pure Python with no numpy/sklearn dependency, because Blueprint 20 is
explicit: "Every dependency removed is a failure mode removed."  The core engine
must be extractable as a standalone library, deterministic, seeded, and free from
I/O.  At our data scale (a few thousand rows, ~15 features, depth-3 trees) a pure
Python implementation trains in well under a second.

The model's authority is deliberately limited (Blueprint 9.3).  It MAY estimate
deterioration, contribute to uncertainty, and SHORTEN CLOCKS.  It MAY NOT veto a
deterministic red flag, lengthen a TTL, independently de-escalate, diagnose,
prescribe, discharge, or autonomously change clinical state.
"""

from __future__ import annotations

import json
import math
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

Monotone = int          # +1 increasing, -1 decreasing, 0 unconstrained


@dataclass
class TreeNode:
    is_leaf: bool = False
    value: float = 0.0
    feature: int = -1
    threshold: float = 0.0
    left: Optional["TreeNode"] = None
    right: Optional["TreeNode"] = None
    # Monotonicity bounds carried down the tree so children cannot violate the
    # constraint their parent established.
    lower: float = -1e18
    upper: float = 1e18

    def to_dict(self) -> Dict[str, Any]:
        if self.is_leaf:
            return {"leaf": round(self.value, 8)}
        return {
            "f": self.feature,
            "t": round(self.threshold, 8),
            "l": self.left.to_dict() if self.left else None,
            "r": self.right.to_dict() if self.right else None,
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "TreeNode":
        if "leaf" in d:
            return TreeNode(is_leaf=True, value=float(d["leaf"]))
        return TreeNode(
            is_leaf=False, feature=int(d["f"]), threshold=float(d["t"]),
            left=TreeNode.from_dict(d["l"]), right=TreeNode.from_dict(d["r"]),
        )


def _predict_tree(node: TreeNode, x: Sequence[float]) -> float:
    while not node.is_leaf:
        node = node.left if x[node.feature] <= node.threshold else node.right
    return node.value


@dataclass
class MonotonicGBM:
    """Binary-outcome gradient boosting with hard monotonic constraints.

    Determinism: no randomness at all unless `subsample` < 1, in which case a
    SEEDED generator is used.  Two runs with the same seed produce byte-identical
    models, which is what the reproducibility guarantee requires.
    """
    feature_names: List[str] = field(default_factory=list)
    monotone_constraints: List[Monotone] = field(default_factory=list)
    n_estimators: int = 40
    learning_rate: float = 0.15
    max_depth: int = 3
    min_samples_leaf: int = 12
    subsample: float = 1.0
    seed: int = 20260825
    base_score: float = 0.0
    trees: List[TreeNode] = field(default_factory=list)
    version: str = "0.9.0"
    trained_on: str = "synthetic cohort generated by app/simulation (disclosed)"

    # ------------------------------------------------------------------
    def fit(self, X: Sequence[Sequence[float]], y: Sequence[float]) -> "MonotonicGBM":
        n = len(X)
        if n == 0:
            self.base_score = 0.0
            return self
        pos = sum(1 for v in y if v > 0.5)
        p = min(max(pos / float(n), 1e-6), 1 - 1e-6)
        self.base_score = math.log(p / (1 - p))

        rng = random.Random(self.seed)
        raw = [self.base_score] * n
        self.trees = []

        for _ in range(self.n_estimators):
            grad: List[float] = []
            hess: List[float] = []
            for i in range(n):
                pr = 1.0 / (1.0 + math.exp(-raw[i]))
                grad.append(pr - float(y[i]))
                hess.append(max(pr * (1 - pr), 1e-6))

            if self.subsample < 1.0:
                idx = [i for i in range(n) if rng.random() < self.subsample]
                if len(idx) < self.min_samples_leaf * 2:
                    idx = list(range(n))
            else:
                idx = list(range(n))

            tree = self._build_tree(X, grad, hess, idx, depth=0,
                                    lower=-1e18, upper=1e18)
            self.trees.append(tree)
            for i in range(n):
                raw[i] += self.learning_rate * _predict_tree(tree, X[i])
        return self

    # ------------------------------------------------------------------
    def _build_tree(self, X, grad, hess, idx: List[int], depth: int,
                    lower: float, upper: float) -> TreeNode:
        leaf_value = self._leaf_value(grad, hess, idx)
        leaf_value = min(max(leaf_value, lower), upper)

        if depth >= self.max_depth or len(idx) < 2 * self.min_samples_leaf:
            return TreeNode(is_leaf=True, value=leaf_value)

        best = self._best_split(X, grad, hess, idx)
        if best is None:
            return TreeNode(is_leaf=True, value=leaf_value)

        feature, threshold, left_idx, right_idx = best
        left_val = self._leaf_value(grad, hess, left_idx)
        right_val = self._leaf_value(grad, hess, right_idx)

        # ---- HARD MONOTONIC CONSTRAINT ---------------------------------
        # For an increasing feature, the RIGHT child (higher feature value) must
        # never predict LOWER than the left child.  We enforce it by clamping the
        # children's admissible ranges, which is what makes "higher respiratory
        # rate never lowers risk" a property rather than a hope.
        c = self.monotone_constraints[feature] if feature < len(self.monotone_constraints) else 0
        left_lower, left_upper = lower, upper
        right_lower, right_upper = lower, upper
        if c != 0:
            mid = (min(max(left_val, lower), upper) + min(max(right_val, lower), upper)) / 2.0
            if c > 0:
                left_upper = min(left_upper, mid)
                right_lower = max(right_lower, mid)
            else:
                left_lower = max(left_lower, mid)
                right_upper = min(right_upper, mid)

        node = TreeNode(is_leaf=False, feature=feature, threshold=threshold,
                        lower=lower, upper=upper)
        node.left = self._build_tree(X, grad, hess, left_idx, depth + 1,
                                     left_lower, left_upper)
        node.right = self._build_tree(X, grad, hess, right_idx, depth + 1,
                                      right_lower, right_upper)
        return node

    def _leaf_value(self, grad, hess, idx: List[int], lam: float = 1.0) -> float:
        if not idx:
            return 0.0
        g = sum(grad[i] for i in idx)
        h = sum(hess[i] for i in idx)
        return -g / (h + lam)

    def _best_split(self, X, grad, hess, idx: List[int]
                    ) -> Optional[Tuple[int, float, List[int], List[int]]]:
        lam = 1.0
        G = sum(grad[i] for i in idx)
        H = sum(hess[i] for i in idx)
        parent_gain = (G * G) / (H + lam)

        best_gain = 1e-7
        best: Optional[Tuple[int, float, List[int], List[int]]] = None
        n_features = len(self.feature_names)

        for f in range(n_features):
            order = sorted(idx, key=lambda i: X[i][f])
            gl = hl = 0.0
            for pos in range(len(order) - 1):
                i = order[pos]
                gl += grad[i]
                hl += hess[i]
                if pos + 1 < self.min_samples_leaf:
                    continue
                if len(order) - (pos + 1) < self.min_samples_leaf:
                    break
                v_here = X[order[pos]][f]
                v_next = X[order[pos + 1]][f]
                if v_here == v_next:
                    continue
                gr = G - gl
                hr = H - hl
                gain = (gl * gl) / (hl + lam) + (gr * gr) / (hr + lam) - parent_gain
                if gain > best_gain:
                    best_gain = gain
                    threshold = (v_here + v_next) / 2.0
                    best = (f, threshold, order[: pos + 1], order[pos + 1:])
        return best

    # ------------------------------------------------------------------
    def predict_raw(self, x: Sequence[float]) -> float:
        raw = self.base_score
        for t in self.trees:
            raw += self.learning_rate * _predict_tree(t, x)
        return raw

    def predict_proba(self, x: Sequence[float]) -> float:
        return 1.0 / (1.0 + math.exp(-self.predict_raw(x)))

    # ------------------------------------------------------------------
    def verify_monotonicity(self, base: Sequence[float], feature_index: int,
                            values: Sequence[float]) -> bool:
        """Blueprint 6.2: 'monotonicity VERIFICATION' is part of the test strategy.

        Sweeps one feature over a range holding everything else fixed and asserts
        the prediction moves only in the constrained direction.
        """
        c = self.monotone_constraints[feature_index]
        if c == 0:
            return True
        x = list(base)
        preds = []
        for v in sorted(values):
            x[feature_index] = v
            preds.append(self.predict_proba(x))
        for a, b in zip(preds, preds[1:]):
            if c > 0 and b < a - 1e-9:
                return False
            if c < 0 and b > a + 1e-9:
                return False
        return True

    def feature_contributions(self, x: Sequence[float]) -> Dict[str, float]:
        """Contribution attribution restricted to a small, monotonic feature set so
        THE TOP DRIVER IS ALWAYS NAMEABLE (Blueprint complexity 7).

        With guaranteed monotonicity, the direction of each contribution is a FACT
        rather than a per-instance estimate.
        """
        baseline = self.predict_raw([0.0] * len(self.feature_names))
        out: Dict[str, float] = {}
        for i, name in enumerate(self.feature_names):
            probe = [0.0] * len(self.feature_names)
            probe[i] = x[i]
            out[name] = self.predict_raw(probe) - baseline
        return out

    # ------------------------------------------------------------------
    def to_dict(self) -> Dict[str, Any]:
        return {
            "version": self.version,
            "feature_names": list(self.feature_names),
            "monotone_constraints": list(self.monotone_constraints),
            "n_estimators": self.n_estimators,
            "learning_rate": self.learning_rate,
            "max_depth": self.max_depth,
            "min_samples_leaf": self.min_samples_leaf,
            "subsample": self.subsample,
            "seed": self.seed,
            "base_score": self.base_score,
            "trained_on": self.trained_on,
            "trees": [t.to_dict() for t in self.trees],
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "MonotonicGBM":
        m = MonotonicGBM(
            feature_names=list(d["feature_names"]),
            monotone_constraints=list(d["monotone_constraints"]),
            n_estimators=int(d["n_estimators"]),
            learning_rate=float(d["learning_rate"]),
            max_depth=int(d["max_depth"]),
            min_samples_leaf=int(d["min_samples_leaf"]),
            subsample=float(d["subsample"]),
            seed=int(d["seed"]),
            base_score=float(d["base_score"]),
            version=d.get("version", "0.9.0"),
            trained_on=d.get("trained_on", ""),
        )
        m.trees = [TreeNode.from_dict(t) for t in d["trees"]]
        return m

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=1)

    @staticmethod
    def load(path: str) -> "MonotonicGBM":
        with open(path, "r", encoding="utf-8") as fh:
            return MonotonicGBM.from_dict(json.load(fh))
